"""add roles and user role foreign key

Revision ID: 04c9489e218d
Revises: e9fb5495ffb9
Create Date: 2026-10-09 09:58:37.835218

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04c9489e218d"
down_revision: str | Sequence[str] | None = "e9fb5495ffb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"], unique=True)
    # Add the FK nullable first so databases with existing users can be upgraded.
    op.add_column("users", sa.Column("role_id", sa.Integer(), nullable=True))

    roles = sa.table(
        "roles",
        sa.column("id", sa.Integer()),
        sa.column("name", sa.String(length=20)),
        sa.column("created_at", sa.DateTime(timezone=True)),
        sa.column("updated_at", sa.DateTime(timezone=True)),
    )
    users = sa.table("users", sa.column("role_id", sa.Integer()))
    now = datetime.now(UTC)
    op.bulk_insert(
        roles,
        [
            {"name": "member", "created_at": now, "updated_at": now},
            {"name": "admin", "created_at": now, "updated_at": now},
        ],
    )
    member_role_id = op.get_bind().execute(
        sa.select(roles.c.id).where(roles.c.name == "member")
    ).scalar_one()
    op.execute(
        users.update()
        .where(users.c.role_id.is_(None))
        .values(role_id=member_role_id)
    )
    op.alter_column("users", "role_id", existing_type=sa.Integer(), nullable=False)
    op.create_foreign_key(
        None, "users", "roles", ["role_id"], ["id"], ondelete="RESTRICT"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "role_id")
    op.drop_index(op.f("ix_roles_name"), table_name="roles")
    op.drop_table("roles")
    # ### end Alembic commands ###
